using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI; // Required to target specific Button components
using System.IO;      // Required to check for save files on the drive
using System.Collections;

public class MainMenuManager : MonoBehaviour
{
    [Header("UI References")]
    [Tooltip("Attach the parent object holding your buttons that has a Canvas Group component.")]
    public CanvasGroup buttonCanvasGroup;

    [Tooltip("Attach the Load Game button here so we can disable it if no save exists.")]
    public ButtonPressEffect customLoadButton;

    [Header("Fade Settings")]
    public float delayBeforeFade = 1.0f;
    public float fadeDuration = 1.5f;

    [Header("Scene Names")]
    public string introSceneName = "IntroScene";
    public string mainGameSceneName = "BeginningArea";

    private void Start()
    {
        // 1. Verify if the player has any save files to load
        CheckForSaveFiles();

        // 2. Instantly hide the button group and prevent clicking on startup
        buttonCanvasGroup.alpha = 0f;
        buttonCanvasGroup.interactable = false;
        buttonCanvasGroup.blocksRaycasts = false;

        // 3. Start the delay and fade process
        StartCoroutine(ShowButtonsRoutine());
    }

    private void CheckForSaveFiles()
    {
        // These are the exact paths generated by your SaveLoadManager
        string quickSavePath = Application.persistentDataPath + "/quicksave.json";
        string checkpointPath = Application.persistentDataPath + "/checkpoint.json";

        // If neither file exists, disable the button
        if (!File.Exists(quickSavePath) && !File.Exists(checkpointPath))
        {
            customLoadButton.gameObject.GetComponent<ButtonPressEffect>().enabled = false;
        }
        else
        {
            customLoadButton.gameObject.GetComponent<ButtonPressEffect>().enabled = false;
        }
    }

    private IEnumerator ShowButtonsRoutine()
    {
        yield return new WaitForSeconds(delayBeforeFade);

        float elapsedTime = 0f;

        while (elapsedTime < fadeDuration)
        {
            elapsedTime += Time.deltaTime;
            buttonCanvasGroup.alpha = Mathf.Clamp01(elapsedTime / fadeDuration);
            yield return null;
        }

        buttonCanvasGroup.alpha = 1f;

        // Make the canvas group active. (This will NOT re-enable the Load button 
        // if we set it to false in CheckForSaveFiles).
        buttonCanvasGroup.interactable = true;
        buttonCanvasGroup.blocksRaycasts = true;
    }

    // --- Button Click Methods ---

    public void OnStartGameClicked()
    {
        Debug.Log("Starting New Game...");
        SceneManager.LoadScene(introSceneName);
    }

    public void OnLoadGameClicked()
    {
        Debug.Log("Loading Save File...");
        string savedScene = SaveLoadManager.Instance.BootUpGame();
        SceneManager.LoadScene(mainGameSceneName);
    }

    public void OnQuitClicked()
    {
        Debug.Log("Quitting Game...");
        Application.Quit();

#if UNITY_EDITOR
        UnityEditor.EditorApplication.isPlaying = false;
#endif
    }
}